CREATE TABLE IF NOT EXISTS video (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    link VARCHAR(255) NOT NULL,
    noplay TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
